## Numpy

In [1]:
import math as m
print(m.sqrt(9))

# if the module is large & we r importing only a part of it :
# from x import y

3.0


In [2]:
import numpy as np

In [31]:
# Creating Numpy arrays
l=[1,2,3,4]
np.array(l)
print(l)

l1=np.zeros(10)
l2=np.ones(9)
print(l1,l2)
print(l1.dtype)
print(l1.shape)

l1=np.zeros(10,int)
print(l1)
print(l1.dtype)

l1[0]=10.32
l1[1]="9" #converts to int
# l1[1]="abc" gives error
print(l1)

[1, 2, 3, 4]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
(10,)
[0 0 0 0 0 0 0 0 0 0]
int32
[10  9  0  0  0  0  0  0  0  0]


In [29]:
#2D Arrays
arr=np.zeros((3,3),int)
print(arr)

print(arr.shape)
print(arr.size)

arr=np.array([[11,20,33],[4,5,6],[7,8,9],[1,2,3],[4,5,6],[7,8,9]])
print(arr)

print(arr.shape)
print(arr.size)

print(arr[0]) # oth row
print(arr[:,0]) # 0th col

print(arr[1:4,0]) # ele 1,2,3 of col - 0


[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)
9
[[11 20 33]
 [ 4  5  6]
 [ 7  8  9]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
(6, 3)
18
[11 20 33]
[11  4  7  1  4  7]
[4 7 1]


In [43]:
# Operations
a=np.array([1,20,3])
b=np.array([14,5,6])
print(a+2) # adding 2 to each ele
print(a)

print(a+b) # each corressponding ele of a added to each corressponding ele of b

print(a*b) # each corressponding ele of a multiplied to each corressponding ele of b

print(a.mean())
print(a.max())
print(a.min())
print(a.dot(b)) # dot product of the 2 arr


[ 3 22  5]
[ 1 20  3]
[15 25  9]
[ 14 100  18]
8.0
20
1
132


In [42]:
# Squared root distance
c=np.array(m.sqrt(((a-b)**2).sum()))
print(c)

20.074859899884732


In [54]:
#Matrices
a=np.matrix('1,2,3;4,5,6')
b=np.matrix('4,5,6;7,8,9')
print(a)

[[1 2 3]
 [4 5 6]]
