<img src="numpy.png" width="500" height="340"> 

In [2]:
import numpy as np

# Zeros

In [7]:
x = np.zeros(5)
print(x)
print(x.dtype)

y = np.array(np.zeros(5), ndmin=10)
print(y)

[0. 0. 0. 0. 0.]
float64
[[[[[[[[[[0. 0. 0. 0. 0.]]]]]]]]]]


# Ones 

In [6]:
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Empty array

In [9]:
x = np.empty(5)
print(x)
print(x.ndim)

[0. 0. 0. 0. 0.]
1


# Range

In [13]:
x = np.arange(6)
print(x)

x = np.arange(2, 6)
print(x)

[0 1 2 3 4 5]
[2 3 4 5]


# Linspace

In [14]:
x = np.linspace(1, 10, 5)
print(x)

[ 1.    3.25  5.5   7.75 10.  ]


# Diagonal

In [16]:
x = np.eye(5)
print(x)

x = np.eye(3, 5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
