<img src="numpy.png" width="340">

In [1]:
import numpy as np

In [7]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])
x = x+2
print(x)
x -= 1
print(x)
z = 1/x
print(z)
z = x+y
print(z)

[3 4 5 6 7]
[2 3 4 5 6]
[0.5        0.33333333 0.25       0.2        0.16666667]
[ 3  5  7  9 11]


<img src="n2.png" height="200">

In [15]:
x = np.array([1, 2, 3, 4, 5])
print(x.max())
print(x.min())
print('Index of min = ', x.argmax())
print('Index of max = ', x.argmin())

print(np.sqrt(x))
print(np.sin(x))
print(np.cumsum(x))  # cumulative sum

5
1
Index of min =  4
Index of max =  0
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 1  3  6 10 15]


In [25]:
x = np.array([[[1, 2, 5, 8], [22, 6, 70, 180], [39, 100, 0, 5]]])
print(x)

# find max for colums axis=0
print(np.max(x, axis=0))

# find max for rows axis=1
print(np.max(x, axis=1))

[[[  1   2   5   8]
  [ 22   6  70 180]
  [ 39 100   0   5]]]
[[  1   2   5   8]
 [ 22   6  70 180]
 [ 39 100   0   5]]
[[ 39 100  70 180]]
