In [1]:
import numpy as np

In [7]:
x = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print(type(x))
print(x.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
(3, 3)


In [9]:
x = np.matrix([[1, 2, 3], [4, 5, 6]])
y = np.matrix([[8, 6, 0], [4, 9, 1]])

z = x-y
print(z)

y = np.matrix([[8, 6, 0], [4, 9, 1], [0, 7, 1]])
z = x*y  # dimensions must satisfy the matrix multiplication criteria
print(z)

z = x.dot(y)  # dimensions must satisfy the matrix multiplication criteria
print(z)

[[-7 -4  3]
 [ 0 -4  5]]
[[ 16  45   5]
 [ 52 111  11]]
[[ 16  45   5]
 [ 52 111  11]]
