<img src="i.png" width="340" >

In [1]:
import numpy as np

In [11]:
x = np.matrix([[1, 2], [4, 6], [7, 9]])

# Transpose
transpose_matrix = np.transpose(x)
print(transpose_matrix)

# Inverse
x = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
inverse_matrix = np.linalg.inv(x)
print(inverse_matrix)

# Power
power_matrix = np.linalg.matrix_power(x, 2)
print(power_matrix)

power_matrix = np.linalg.matrix_power(x, 0) # fill diag with 1s and other 0s
print(power_matrix)

power_matrix = np.linalg.matrix_power(x, -2)
print(power_matrix)

# Determinant
determinant = np.linalg.det(x)
print(determinant)

[[1 4 7]
 [2 6 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ 5.96302842e+31 -1.19260568e+32  5.96302842e+31]
 [-1.19260568e+32  2.38521137e+32 -1.19260568e+32]
 [ 5.96302842e+31 -1.19260568e+32  5.96302842e+31]]
-9.51619735392994e-16
<class 'numpy.float64'>
