# Search - np.where()

In [1]:
import numpy as np

In [4]:
x = np.array([5, 8, 3, 6, 9, 1, 7])
#             0  1  2  3  4  5  6

# np.where() returns array of indices
res = np.where(x == 8)
print(res)

res = np.where(x % 2 == 0)
print(res)

(array([1], dtype=int64),)
(array([1, 3], dtype=int64),)


# Sort - np.sort()

In [11]:
x = np.array([5, 8, 3, 6, 9, 1, 7])
res = np.sort(x)
print(res)

[1 3 5 6 7 8 9]


In [9]:
x = np.array([[5, 8, 3, 6, 4], [9, 6, 7, 1, 0]])
res = np.sort(x)
print(res)

[[3 4 5 6 8]
 [0 1 6 7 9]]


# Filter - np.filter()

In [10]:
x = np.array([5, 8, 3, 6, 9, 1, 7])
f = [True, False, True, False, False, True, False,]

res=x[f]

print(res)

[5 3 1]
