# Insert

In [25]:
import numpy as np

In [33]:
x = np.array([5, 8, 3, 6, 9, 1, 7])
#             0  1  2  3  4  5  6

res = np.insert(x, 3, 10)  # pos ele
print(res)

res = np.insert(x, [3, 5], 10)  # pos ele
print(res)

res = np.insert(x, [3, 5], [10, 20])  # pos ele
print(res)

res = np.insert(x, [3, 5], [10, 20])  # pos ele
print(res)

[ 5  8  3 10  6  9  1  7]
[ 5  8  3 10  6  9 10  1  7]
[ 5  8  3 10  6  9 20  1  7]
[ 5  8  3 10  6  9 20  1  7]


In [42]:
x = np.array([[5, 8, 3, 6, 4], [9, 6, 7, 1, 0]])

res = np.insert(x, 1, 6, axis=1) # 1 - column
print(res)

res = np.insert(x, 1, 6, axis=0) # 0 - row
print(res)

res = np.insert(x, 1, [0, 1, 4, 9 , 10], axis=0)
print(res)

[[5 6 8 3 6 4]
 [9 6 6 7 1 0]]
[[5 8 3 6 4]
 [6 6 6 6 6]
 [9 6 7 1 0]]
[[ 5  8  3  6  4]
 [ 0  1  4  9 10]
 [ 9  6  7  1  0]]


# Append

In [48]:
x = np.array([5, 8, 3, 6, 9, 1, 7])
#             0  1  2  3  4  5  6

res = np.append(x, 10)  # ele
print(res)

res = np.append(x, [10, 50])  # ele
print(res)

[ 5  8  3  6  9  1  7 10]
[ 5  8  3  6  9  1  7 10 50]
[ 5  8  3 10  6  9 20  1  7]
[ 5  8  3 10  6  9 20  1  7]


In [53]:
x = np.array([[5, 8, 3], [9, 6, 7]])

res = np.append(x, [[6, 10, 2]], axis=0)  # 1 - column
print(res)

[[ 5  8  3]
 [ 9  6  7]
 [ 6 10  2]]


# Delete

In [61]:
x = np.array([5, 8, 10, 6, 9, 1, 7])
#             0  1  2  3  4  5  6

res = np.delete(x, 2)  # pos ele
print(res)

x = np.array([[5, 1, 3, 6, 4], [9, 10, 7, 1, 0]])

res = np.delete(x, 1, axis=1) # 1 - column
print(res)

res = np.delete(x, 1, axis=0) # 1 - column
print(res)

[5 8 6 9 1 7]
[[5 3 6 4]
 [9 7 1 0]]
[[5 1 3 6 4]]


# Search - np.where()

In [4]:
x = np.array([5, 8, 3, 6, 9, 1, 7])
#             0  1  2  3  4  5  6

# np.where() returns array of indices
res = np.where(x == 8)
print(res)

res = np.where(x % 2 == 0)
print(res)

(array([1], dtype=int64),)
(array([1, 3], dtype=int64),)


# Sort - np.sort()

In [11]:
x = np.array([5, 8, 3, 6, 9, 1, 7])
res = np.sort(x)
print(res)

[1 3 5 6 7 8 9]


In [9]:
x = np.array([[5, 8, 3, 6, 4], [9, 6, 7, 1, 0]])
res = np.sort(x)
print(res)

[[3 4 5 6 8]
 [0 1 6 7 9]]


# Filter - np.filter()

In [10]:
x = np.array([5, 8, 3, 6, 9, 1, 7])
f = [True, False, True, False, False, True, False,]

res=x[f]

print(res)

[5 3 1]


# Shuffle - np.random.shuffle()

In [15]:
x = np.array([5, 8, 3, 6, 9, 1, 7])
np.random.shuffle(x)
print(x)

[3 6 5 1 7 8 9]


# Unique - np.unique()

In [20]:
x = np.array([5, 5, 3, 6, 9, 6, 5])
res = np.unique(x)
print(res)
res = np.unique(x, return_index=True)
print(res)
res = np.unique(x, return_index=True, return_counts=True)
print(res)

[3 5 6 9]
(array([3, 5, 6, 9]), array([2, 0, 3, 4], dtype=int64))
(array([3, 5, 6, 9]), array([2, 0, 3, 4], dtype=int64), array([1, 3, 2, 1], dtype=int64))


# Resize - np.resize()

In [22]:
x = np.array([5, 8, 3, 6, 9, 1, 7, 0])
res = np.resize(x, (4, 2))
print(res)
res = np.resize(x, (2, 2, 2))
print(res)

[[5 8]
 [3 6]
 [9 1]
 [7 0]]
[[[5 8]
  [3 6]]

 [[9 1]
  [7 0]]]


# Flatten 

In [24]:
x = np.array([[5, 8, 3, 6, 4], [9, 6, 7, 1, 0]])
res = x.flatten()
print(res)

[5 8 3 6 4 9 6 7 1 0]
