# Indexing

In [1]:
import numpy as np

In [2]:
x = np.array([0, 1, 2, 3, 4])
#             0  1  2  3  4   
#             -5 -4 -3 -2 -1  

print(x[0])
print(x[-5])

0
0


In [4]:
x = np.array([[5, 8, 3, 6, 4], [9, 6, 7, 1, 0]])
# 2 lists -    list 1           list 2
#              0  1  2  3  4    0  1  2  3  4

print(x[0])
print(x[1])

print(x[0][2])

[5 8 3 6 4]
[9 6 7 1 0]
3


In [13]:
# x = np.array([[[5, 8, 3, 6, 4], [9, 6, 7, 1, 0]], [[5, 8, 3, 6, 4]]])
# error - same no of lists and same no of elements in each list

x = np.array([[[5, 8, 3, 6, 4], [9, 6, 7, 1, 0]], [[4, 8, 1, 9, 2], [3, 1, 7, 5, 8]]])
# 2 lists -    list 1                             list 2
#              0  1  2  3  4    0  1  2  3  4       0  1  2  3  4     0  1  2  3  4

print(x[0])
print(x[1])
print(x[1][0][4])

[[5 8 3 6 4]
 [9 6 7 1 0]]
[[4 8 1 9 2]
 [3 1 7 5 8]]
2


In [22]:
x = np.array([[[[[5, 8, 3, 6, 4]]]]])
print(x)
print(x.shape)

print()
print(x[0])
print(x[0][0])
print(x[0][0][0])
print(x[0][0][0][0])
print(x[0][0][0][0][1])

[[[[[5 8 3 6 4]]]]]
(1, 1, 1, 1, 5)

[[[[5 8 3 6 4]]]]
[[[5 8 3 6 4]]]
[[5 8 3 6 4]]
[5 8 3 6 4]
8
