<img src="img.png" width="580" height="200" >

# Examples

<img src="i2.png" width="400" height="200" >
<img src="i4.png" width="400" height="216" >
<img src="i3.png" width="400" height="200" >

# Rules for Broadcasting

<img src="i5.png" width="580" height="500" >

In [1]:
import numpy as np

In [7]:
x=np.array([1,2,3,4,5])
print(x.shape) # 5

y=np.array([5]) 
print(y.shape) # 1

# Broadcasting - 5 & 1 we have 1 
z=x+y 
print(z)
print(z.shape) # always takes max so (5,)

(5,)
(1,)
[ 6  7  8  9 10]
(5,)


In [9]:
x=np.array([[1,2,3,4,5], [1,2,3,4,5]])
print(x.shape) # 2 5

y=np.array([[3,4,5,6,7]])
print(y.shape) # 1 5

# Broadcasting - 2 5 and 1 5 -> 5,5 equal and 2,1 have 1
z=x+y 
print(z)
print(z.shape) # always takes max so (2,5)

(2, 5)
(1, 5)
[[ 4  6  8 10 12]
 [ 4  6  8 10 12]]
(2, 5)
