In [1]:
import numpy as np

In [6]:
x = np.array([5, 8, 3, 6, 9, 1, 7])
#             0  1  2  3  4  5  6

print(x)
print(x[:])     # 0  1  2  3  4  5  6
print(x[:5])    # 0  1  2  3  4
print(x[2:5])   # 2  3  4
print(x[3:])    # 3  4  5  6

[5 8 3 6 9 1 7]
[5 8 3 6 9 1 7]
[5 8 3 6 9]
[3 6 9]
[6 9 1 7]


In [7]:
x = np.array([[5, 8, 3, 6, 4], [9, 6, 7, 1, 0]])
# 2 lists -    list 1           list 2
#              0  1  2  3  4    0  1  2  3  4

print(x)
print(x[0][1:4])

[[5 8 3 6 4]
 [9 6 7 1 0]]
[8 3 6]
