# Shape

In [2]:
import numpy as np

In [12]:
x=np.array([1,2,3,4,5])
print(x.shape) # x has a shape of (5,) - it has 5 elements 

(5,)


In [13]:
x = np.array([[1, 2, 5, 8], [3,4,8,10]])
print(x.shape) # 2 lists each has 4 elements

x = np.array([[1, 2, 5, 8], [22, 6, 70, 180], [3,4,8,10]])
print(x.shape) # 3 lists each has 4 elements

(2, 4)
(3, 4)


In [3]:
x = np.array([[[1, 2, 5, 8], [22, 6, 70, 180], [39, 100, 0, 5]]])
print(x.shape) # (1, 3, 4) - 1 list, inside has 3 lists, each has 4 ele

x = np.array([[[1, 2, 5, 8], [22, 6, 70, 180], [39, 100, 0, 5]], [[1, 2, 5, 8], [22, 6, 70, 180], [39, 100, 0, 5]]])
print(x.shape) # (2, 3, 4) - 2 lists, inside has 3 lists, each has 4 ele

x=np.array([[1,2,3],[4,5,6]],ndmin=5)
print(x)
print(x.shape)

(1, 3, 4)
(2, 3, 4)
[[[[[1 2 3]
    [4 5 6]]]]]
(1, 1, 1, 2, 3)


# Reshape

In [20]:
x=np.array([1,2,3,4,5,6])

y=x.reshape(3,2) 
print(y.shape)
print(y.ndim)

y=x.reshape(1,3,2) 
print(y)
print(y.shape)
print(y.ndim)

x=np.array([1,2,3,4,5,6,1,2,3,4,5,6])
y=x.reshape(2,2,3) 
print(y)
print(y.shape)
print(y.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2
[[[1 2]
  [3 4]
  [5 6]]]
(1, 3, 2)
3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3
