In [1]:
import numpy as np

# View or Shallow Copy

In [4]:
x = np.array([5, 8, 3, 6, 9, 1, 7])

x_view = x.view()

print(x)
print(x_view)

x_view += 2

print(x)
print(x_view)

[5 8 3 6 9 1 7]
[5 8 3 6 9 1 7]
[ 7 10  5  8 11  3  9]
[ 7 10  5  8 11  3  9]


# Deep Copy

In [3]:
x = np.array([5, 8, 3, 6, 9, 1, 7])

x_copy = x.copy()

print(x)
print(x_copy)

x_copy += 2

print(x)
print(x_copy)

[5 8 3 6 9 1 7]
[5 8 3 6 9 1 7]
[5 8 3 6 9 1 7]
[ 7 10  5  8 11  3  9]
