In [1]:
import numpy as np

In [2]:
# 1D array
ar1=np.array([1,2,3])
print(ar1)
print(ar1.ndim)

# 2D array
ar2=np.array([[1,2,3,4], [5,6,7,8]])
print(ar2)
print(ar2.ndim)

# 3D array
ar3=np.array([[[1,1,1,1], [1,1,1,1], [1,1,1,1]]])
print(ar3)
print(ar3.ndim)

# N-D array using ndmin
arn=np.array([[1,2,3], [4,5,6]], ndmin=10)
print(arn)
print(arn.ndim)

[1 2 3]
1
[[1 2 3 4]
 [5 6 7 8]]
2
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
3
[[[[[[[[[[1 2 3]
         [4 5 6]]]]]]]]]]
10
